"""add_motivo_rechazo_to_vehiculo

Revision ID: 7beb62ff66be
Revises: b136e072bcfd
Create Date: 2026-05-16 17:49:29.886298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7beb62ff66be'
down_revision: Union[str, Sequence[str], None] = 'b136e072bcfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehiculos', sa.Column('motivo_rechazo', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehiculos', 'motivo_rechazo')
    # ### end Alembic commands ###
