"""Add legal fields to Vehiculo

Revision ID: 88aa4fbb3a6a
Revises: 858ccb724bbc
Create Date: 2026-05-13 03:38:07.482409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88aa4fbb3a6a'
down_revision: Union[str, Sequence[str], None] = '858ccb724bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehiculos', sa.Column('patente', sa.String(length=20), nullable=True))
    op.add_column('vehiculos', sa.Column('chasis', sa.String(length=50), nullable=True))
    op.add_column('vehiculos', sa.Column('motor', sa.String(length=50), nullable=True))
    op.add_column('vehiculos', sa.Column('titular', sa.String(length=100), nullable=True))
    op.add_column('vehiculos', sa.Column('cedula', sa.String(length=50), nullable=True))
    op.add_column('vehiculos', sa.Column('poliza', sa.String(length=50), nullable=True))
    op.add_column('vehiculos', sa.Column('vtv', sa.String(length=50), nullable=True))
    op.add_column('vehiculos', sa.Column('estacion', sa.String(length=100), nullable=True))
    op.add_column('vehiculos', sa.Column('telefono', sa.String(length=50), nullable=True))
    op.add_column('vehiculos', sa.Column('descripcion', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehiculos', 'descripcion')
    op.drop_column('vehiculos', 'telefono')
    op.drop_column('vehiculos', 'estacion')
    op.drop_column('vehiculos', 'vtv')
    op.drop_column('vehiculos', 'poliza')
    op.drop_column('vehiculos', 'cedula')
    op.drop_column('vehiculos', 'titular')
    op.drop_column('vehiculos', 'motor')
    op.drop_column('vehiculos', 'chasis')
    op.drop_column('vehiculos', 'patente')
    # ### end Alembic commands ###
