"""add_testimonio_table

Revision ID: 9f34c00c4301
Revises: 751e6f315d25
Create Date: 2026-06-07 15:02:52.870624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f34c00c4301'
down_revision: Union[str, Sequence[str], None] = '751e6f315d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testimonios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reserva_id', sa.Uuid(), nullable=False),
    sa.Column('conductor_id', sa.Uuid(), nullable=False),
    sa.Column('vehiculo_id', sa.Uuid(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conductor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reserva_id', name='uq_testimonios_reserva_id')
    )
    op.create_index(op.f('ix_testimonios_conductor_id'), 'testimonios', ['conductor_id'], unique=False)
    op.create_index(op.f('ix_testimonios_reserva_id'), 'testimonios', ['reserva_id'], unique=True)
    op.create_index(op.f('ix_testimonios_vehiculo_id'), 'testimonios', ['vehiculo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_testimonios_vehiculo_id'), table_name='testimonios')
    op.drop_index(op.f('ix_testimonios_reserva_id'), table_name='testimonios')
    op.drop_index(op.f('ix_testimonios_conductor_id'), table_name='testimonios')
    op.drop_table('testimonios')
    # ### end Alembic commands ###
