"""agrego vehiculos y fotos

Revision ID: a8385185e33e
Revises: 48c2ca1410ce
Create Date: 2026-05-12 09:05:32.754007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8385185e33e'
down_revision: Union[str, Sequence[str], None] = '48c2ca1410ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiculos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('propietario_id', sa.Uuid(), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('tipo_transmision', sa.String(length=50), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('tipo_combustible', sa.String(length=50), nullable=False),
    sa.Column('pets_friendly', sa.Boolean(), nullable=False),
    sa.Column('estado_registro', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['propietario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculos_propietario_id'), 'vehiculos', ['propietario_id'], unique=False)
    op.create_table('fotos_vehiculo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehiculo_id', sa.Uuid(), nullable=False),
    sa.Column('lado', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('formato', sa.String(length=20), nullable=False),
    sa.Column('tamanio_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fotos_vehiculo_vehiculo_id'), 'fotos_vehiculo', ['vehiculo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fotos_vehiculo_vehiculo_id'), table_name='fotos_vehiculo')
    op.drop_table('fotos_vehiculo')
    op.drop_index(op.f('ix_vehiculos_propietario_id'), table_name='vehiculos')
    op.drop_table('vehiculos')
    # ### end Alembic commands ###
