"""US_2C_add_estado_habilitacion_y_motivo

Revision ID: a98d562147ec
Revises: e4f3a5c8d100
Create Date: 2026-05-23 13:08:19.030280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a98d562147ec'
down_revision: Union[str, Sequence[str], None] = 'e4f3a5c8d100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE estado_habilitacion_enum AS ENUM ('PENDIENTE_REVISION', 'APROBADO', 'RECHAZADO')")
    op.add_column('documentacion_habilitante_conductor', sa.Column('motivo_rechazo', sa.Text(), nullable=True))
    op.execute(
        "ALTER TABLE documentacion_habilitante_conductor "
        "ALTER COLUMN estado_validacion TYPE estado_habilitacion_enum "
        "USING estado_validacion::estado_habilitacion_enum"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documentacion_habilitante_conductor', 'estado_validacion',
               existing_type=sa.Enum('PENDIENTE_REVISION', 'APROBADO', 'RECHAZADO', name='estado_habilitacion_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('documentacion_habilitante_conductor', 'motivo_rechazo')
    # ### end Alembic commands ###
