"""agrego_estado_disponible_us9d

Revision ID: b136e072bcfd
Revises: af99ccbfc627
Create Date: 2026-05-16 14:59:09.923983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b136e072bcfd'
down_revision: Union[str, Sequence[str], None] = 'af99ccbfc627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehiculos', sa.Column('disponible', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehiculos', 'disponible')
    # ### end Alembic commands ###
