"""Add reportes table

Revision ID: ba20a786928a
Revises: b7f3c1a9d2e4
Create Date: 2026-06-17 13:38:47.996964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba20a786928a'
down_revision: Union[str, Sequence[str], None] = 'b7f3c1a9d2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reserva_id', sa.Uuid(), nullable=False),
    sa.Column('conductor_id', sa.Uuid(), nullable=False),
    sa.Column('vehiculo_id', sa.Uuid(), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=False),
    sa.Column('url_foto_adjuntada', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conductor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportes_conductor_id'), 'reportes', ['conductor_id'], unique=False)
    op.create_index(op.f('ix_reportes_reserva_id'), 'reportes', ['reserva_id'], unique=True)
    op.create_index(op.f('ix_reportes_vehiculo_id'), 'reportes', ['vehiculo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reportes_vehiculo_id'), table_name='reportes')
    op.drop_index(op.f('ix_reportes_reserva_id'), table_name='reportes')
    op.drop_index(op.f('ix_reportes_conductor_id'), table_name='reportes')
    op.drop_table('reportes')
    # ### end Alembic commands ###
