"""Add valoraciones and calificacion_promedio

Revision ID: d5af9c7fcba7
Revises: dfcfd163fc92
Create Date: 2026-06-07 01:27:14.985642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5af9c7fcba7'
down_revision: Union[str, Sequence[str], None] = 'dfcfd163fc92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('valoraciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reserva_id', sa.Uuid(), nullable=False),
    sa.Column('conductor_id', sa.Uuid(), nullable=False),
    sa.Column('vehiculo_id', sa.Uuid(), nullable=False),
    sa.Column('puntaje', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conductor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reserva_id', name='uq_valoraciones_reserva_id')
    )
    op.create_index(op.f('ix_valoraciones_conductor_id'), 'valoraciones', ['conductor_id'], unique=False)
    op.create_index(op.f('ix_valoraciones_reserva_id'), 'valoraciones', ['reserva_id'], unique=True)
    op.create_index(op.f('ix_valoraciones_vehiculo_id'), 'valoraciones', ['vehiculo_id'], unique=False)
    op.add_column('usuarios', sa.Column('calificacion_promedio', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('vehiculos', sa.Column('calificacion_promedio', sa.Numeric(precision=3, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehiculos', 'calificacion_promedio')
    op.drop_column('usuarios', 'calificacion_promedio')
    op.drop_index(op.f('ix_valoraciones_vehiculo_id'), table_name='valoraciones')
    op.drop_index(op.f('ix_valoraciones_reserva_id'), table_name='valoraciones')
    op.drop_index(op.f('ix_valoraciones_conductor_id'), table_name='valoraciones')
    op.drop_table('valoraciones')
    # ### end Alembic commands ###
