"""US_2C_add_estado_habilitacion_enum_y_motivo_rechazo

Revision ID: de8fbc80e3cd
Revises: d5b8e2f30412
Create Date: 2026-05-23 01:38:18.977991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de8fbc80e3cd'
down_revision: Union[str, Sequence[str], None] = 'd5b8e2f30412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documentacion_habilitante_conductor_usuario_id'), table_name='documentacion_habilitante_conductor')
    op.drop_table('documentacion_habilitante_conductor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentacion_habilitante_conductor',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('numero_licencia', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('fecha_emision', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('fecha_vencimiento', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('foto_licencia_frente_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('foto_licencia_dorso_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('estado_validacion', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('documentacion_habilitante_conductor_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('documentacion_habilitante_conductor_pkey')),
    sa.UniqueConstraint('usuario_id', name=op.f('uq_documentacion_habilitante_conductor_usuario_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_documentacion_habilitante_conductor_usuario_id'), 'documentacion_habilitante_conductor', ['usuario_id'], unique=False)
    # ### end Alembic commands ###
