"""add_lat_lng_estaciones

Revision ID: dfcfd163fc92
Revises: e228ec676a1f
Create Date: 2026-06-03 00:39:23.703759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfcfd163fc92'
down_revision: Union[str, Sequence[str], None] = 'd3b9c4e1f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estaciones', sa.Column('latitud', sa.Float(), nullable=True))
    op.add_column('estaciones', sa.Column('longitud', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estaciones', 'longitud')
    op.drop_column('estaciones', 'latitud')
    # ### end Alembic commands ###
