"""us15c_checkin_vehiculo

Revision ID: fa25e87da86c
Revises: a3b1c8d2e9f4
Create Date: 2026-05-31 01:57:51.634658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa25e87da86c'
down_revision: Union[str, Sequence[str], None] = 'a3b1c8d2e9f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkins_vehiculo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reserva_id', sa.Uuid(), nullable=False),
    sa.Column('conductor_id', sa.Uuid(), nullable=False),
    sa.Column('nivel_combustible', sa.String(length=20), nullable=False),
    sa.Column('kilometraje_actual', sa.Integer(), nullable=False),
    sa.Column('esta_limpio', sa.Boolean(), nullable=False),
    sa.Column('tiene_danios', sa.Boolean(), nullable=False),
    sa.Column('descripcion_danios', sa.String(length=500), nullable=True),
    sa.Column('url_foto_frente', sa.String(length=255), nullable=False),
    sa.Column('url_foto_trasera', sa.String(length=255), nullable=False),
    sa.Column('url_foto_lateral_izq', sa.String(length=255), nullable=False),
    sa.Column('url_foto_lateral_der', sa.String(length=255), nullable=False),
    sa.Column('url_foto_panel', sa.String(length=255), nullable=False),
    sa.Column('urls_fotos_danios', sa.JSON(), nullable=False),
    sa.Column('url_foto_extra', sa.String(length=255), nullable=True),
    sa.Column('notas_adicionales', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('motivo_rechazo', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conductor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_vehiculo_conductor_id'), 'checkins_vehiculo', ['conductor_id'], unique=False)
    op.create_index(op.f('ix_checkins_vehiculo_estado'), 'checkins_vehiculo', ['estado'], unique=False)
    op.create_index(op.f('ix_checkins_vehiculo_reserva_id'), 'checkins_vehiculo', ['reserva_id'], unique=True)
    op.drop_constraint(op.f('reservas_codigo_key'), 'reservas', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('reservas_codigo_key'), 'reservas', ['codigo'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_checkins_vehiculo_reserva_id'), table_name='checkins_vehiculo')
    op.drop_index(op.f('ix_checkins_vehiculo_estado'), table_name='checkins_vehiculo')
    op.drop_index(op.f('ix_checkins_vehiculo_conductor_id'), table_name='checkins_vehiculo')
    op.drop_table('checkins_vehiculo')
    # ### end Alembic commands ###
